### ISSUE TITLE
Google Search Console says "Couldn't Fetch"

### ISSUE THREAD

**Issue by NichtsHsu** [jekyll/jekyll-sitemap#302]
I'm using `jekyll-sitemap` to generate sitemap for my blog, url is <https://nihil.cc/sitemap.xml>. When I try to add it to sitemap on Google Search Console, it tells me that "Couldn't Fetch". Some say adding a forward slash works, but `https://nihil.cc//sitemap.xml` still gives me a "Couldn't Fetch".

Can anyone give some suggestions?

**Comment by cortix** [comment]
You need to make sure that the `url` in the `_config.yml` file is set as follows;

```
url                      : https://nihil.cc
```

**Comment by NichtsHsu** [comment]
Hi @cortix ,

Thanks for your reply, I'm sure I have configured it correctly:

https://github.com/NichtsHsu/nichtshsu.github.io/blob/3d3a3846ef4d49602572fff8de90960252b0526a/_config.yml#L27

**Comment by cortix** [comment]
Interesting!! You can see `sitemap.xml` in the root directory of the created `_site` folder, right? I'm just asking to be sure. Maybe the sitemap is not rendering properly.

**Comment by NichtsHsu** [comment]
> You can see sitemap.xml in the root directory of the created _site folder

Yes, it is.

**Comment by ashmaroli** [comment]
Could you post a screenshot of the actual error rendering on your browser?

**Comment by NichtsHsu** [comment]
Hi @ashmaroli ,

![image](https://user-images.githubusercontent.com/35688135/209967718-124b897a-857a-4cdf-a728-656c31990f6f.png)

**Comment by cortix** [comment]
I suppose, the problem is caused by subdomain.

**Comment by cortix** [comment]
When I looked at the https://gm8.nihil.cc//sitemap.xml, I got this result...

<img width="1104" alt="Screenshot 2022-12-29 at 17 42 28" src="https://user-images.githubusercontent.com/6178404/209969062-c3bc47d9-9cc0-41fc-977a-2cda8d3c89c3.png">

You said earlier that you set the `url` as "`https://nihil.cc`". You have to do same thing for subdomain.

**Comment by ashmaroli** [comment]
@NichtsHsu Thanks for the screenshot.
I thought you had added an entry for `https://nihil.cc//sitemap.xml` as well.. but don't see that in your listing.

**Comment by ashmaroli** [comment]
Regarding validation, the two links seem good as per following:
- https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fnihil.cc%2Fsitemap.xml&submit=Validate+Sitemap
- https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fgm8.nihil.cc%2Fsitemap.xml&submit=Validate+Sitemap

**Comment by ashmaroli** [comment]
@NichtsHsu In the GSC Dashboard Sidebar, try adding the sitemap url to the property `https://nihil.cc/` **instead of `nihil.cc (DOMAIN PROPERTY)`**.

**Comment by cortix** [comment]
I had gotten a similar error too. If I'm not mistaken, this problem is related to the subdomain. When you set the `url` as `https://nihil.cc`  in `_config.yml`, I guess the Jekyll-sitemap plugin creates a sitemap just for it by overriding localhost to `https://nihil.cc`. I had solved this problem by creating a separate template for the subdomain and in this separate template, I had set the `url` as subdomain. If you notice,

Your `https://gm8.nihil.cc//sitemap.xml` shows up like this,

<img width="1104" alt="Screenshot 2022-12-29 at 17 42 28" src="https://user-images.githubusercontent.com/6178404/209969062-c3bc47d9-9cc0-41fc-977a-2cda8d3c89c3.png">

while the other sitemap shows up like this;

<img width="1104" alt="Screenshot 2022-12-29 at 18 20 45" src="https://user-images.githubusercontent.com/6178404/209973741-1e7d7948-1d1d-40a1-9d09-ab1741861fbd.png">

**Comment by NichtsHsu** [comment]
> I suppose, the problem is caused by subdomain.

Now I fixed the sitemap of my subdomain, but not improved.

> I thought you had added an entry for https://nihil.cc//sitemap.xml as well.. but don't see that in your listing.

When I tried to add `https://nihil.cc//sitemap.xml`, GSC automatically changed it to `https://nihil.cc/sitemap.xml`.

> try adding the sitemap url to the property `https://nihil.cc/` instead of `nihil.cc`

I tried `sitemap.xml` and `/sitemap.xml`:

![image](https://user-images.githubusercontent.com/35688135/209974787-4eeea329-118b-4c03-96ee-3142e6a719d7.png)

**Comment by ashmaroli** [comment]
@NichtsHsu The property entry for `https://nihil.cc/` look good to me. Let's wait for a couple of days to see if Google's crawlers  report positively after getting plenty of time to crawl through every link in `/sitemap.xml`.

**Comment by NichtsHsu** [comment]
Response after one month: GSC still can't fetch my sitemap.

But a funny thing happened: the sitemap itself is indexed when none of my new posts are indexed:

![image](https://user-images.githubusercontent.com/35688135/216222390-59383df6-4bbe-496c-834c-485a8a3c77a0.png)

**Comment by ashmaroli** [comment]
I feel sorry that this is still an issue, @NichtsHsu. Have you tried reaching out to Google support team? Perhaps, they can tell you what exactly is wrong... 🤷‍♂️

**Comment by NichtsHsu** [comment]
It seems that there are already a lot of the same issue in the Google search console community, and most people don't get a working solution. I just tested Bing Webmaster Tool and it fetch my sitemap just fine. So it looks like I have nothing to do but fxxk Google.

**Comment by Emojigit** [comment]
Workaround: Add a redirect from the main (www or apex) website to the target website's sitemap. Below is an example when using Cloudflare Pages redirect:
```
/sitemap_blog.xml https://blog.example.com/sitemap.xml
```
Then submit the sitemap URL on the main website (i.e. `https://www.example.com/sitemap_blog.xml`) to Google.
